### ISSUE TITLE
error  : Le SDK 'Microsoft.NET.Sdk' spécifié est introuvable

### ISSUE THREAD

**Issue by Owned67** [collectVood/PlayerCountBot#2]
Hello,

I'm trying to get the .exe but can't compile without error...

I've installed dotnet-sdk-2.1.518-win-x64.exe, apparently is not good, can you explain what i'l need please?

Thanks

**Comment by collectVood** [comment]
If you just want the pre-compiled .exe you can head over to the release section. Otherwise you need the dotnet 3.1 and higher sdk

**Comment by Owned67** [comment]
Ok thanks found release, it's good 👍
