### ISSUE TITLE
 Region request failed : Code BadRequest &  A Ready handler is blocking the gateway task.

### ISSUE THREAD

**Issue by Owned67** [collectVood/PlayerCountBot#3]
`{
  "Discord refresh (seconds)": 30,
  "Reconnect delay (seconds)": 10,
  "Create output file": false,
  "Steam API Key": "mytoken1234",
  "Servers": [
    {
      "Discord": {
        "Bot Token": "mytoken1234",
        "Guild ID": 268426701401227264,
        "Activity type (0 = Playing, 1 = Streaming, 2 = Listening, 3 = Watching)": 0
      },
      "Rcon": {
        "Server IP": "192.168.1.15",
        "Rcon Port": "29135",
        "Rcon Password": "12345",
        "Server Port (Optional only used in ServerInfo Embed)": "29130"
      },
      "Chatlog": {
        "Use Chatlog": true,
        "Chatlog Webhook Url": "https://discordapp.com/api/webhooks/712634775612948520/1q-0hXldAzwvajQaEyvqhusPs9W9XORdrMguOMlOj-vGt23YWHCTWXDGC1hqEyl7BqVf",
        "Command Prefix": "!",
        "Chatlog Channel Id": 585887992296505355,
        "Default Name Color (for send messages when no steamId provided)": "#af5",
        "Server Message Colour (RGB)": {
          "Red": 255,
          "Green": 0,
          "Blue": 0
        },
        "Can Use Commands Role Ids": [
          0,
          0
        ],
        "Show team chat": true
      },
      "Serverinfo": {
        "Server info channel ID": 701852189202710579,
        "Show player count in status": true,
        "Status message (only if player count is not shown in status)": "",
        "Get server region data over (https://ipinfo.io)": true,
        "Show server info in embed": true,
        "Server info embed title hyperlink": "",
        "Server info embed color (RGB)": {
          "Red": 44,
          "Green": 47,
          "Blue": 51
        }
      },
      "Localization": {
        "Player Count Status": "{0} / {1} {2}",
        "Embed Title": "{0} {1}",
        "Embed Description": "{0}:{1}",
        "Embed Footer": "Last Wiped {0}",
        "Embed Field Player": {
          "Name": "Players",
          "Value": "{0}",
          "Inline": true
        },
        "Embed Field FPS": {
          "Name": "FPS",
          "Value": "{0}",
          "Inline": true
        },
        "Embed Field Entities": {
          "Name": "Entities",
          "Value": "{0}",
          "Inline": true
        },
        "Embed Field Game time": {
          "Name": "Game time",
          "Value": "{0}",
          "Inline": true
        },
        "Embed Field Uptime": {
          "Name": "Uptime",
          "Value": "{0}",
          "Inline": true
        },
        "Embed Field Map": {
          "Name": "Map",
          "Value": "[View here]({0})",
          "Inline": true
        }
      }
    }
  ],
  "Staff Discord & SteamIds (Key: DiscordId; Value: SteamId)": {
    "0": 0,
    "247XXXXXXXXXXXXXX": 765611XXXXXXXXXX
  },
  "Debug": true
}`

> [DEBUG - 16/10/2020 16:39:08] Bot - Received message with idenfitier : 101
> [DEBUG - 16/10/2020 16:39:08] Bot  - Received message with idenfitier : 102
> [DEBUG - 16/10/2020 16:39:08] Bot  - Received message with idenfitier : 100
> [DEBUG - 16/10/2020 16:39:09] Bot  - Region request failed : Code BadRequest
> [16/10/2020 16:39:11] Bot  - A Ready handler is blocking the gateway task.

**Comment by collectVood** [comment]
Hey, you can ignore the 'A Ready handler is blocking the gateway task.'  since this is caused by a dumb way of using the Ready method on my part. It should not actually cause any issues though. 

In regards to the Bad Request, I'll check that out later today just to see if possibly the site now requires a different request syntax.

**Comment by collectVood** [comment]
I had another look at it and seems to still be all the same. Is the IP you specified valid?

**Comment by collectVood** [comment]
Re-open if you are still encountering this issue
