### ISSUE TITLE
Rusty Watcher -  Error: Unable to get current guild

### ISSUE THREAD

**Issue by SmokeBudz93** [collectVood/PlayerCountBot#5]
I keep getting this messange after everything i do i cannot get it to work with my server 

Rusty Watcher -  Error: Unable to get current guild

**Comment by collectVood** [comment]
Make sure the bot is in the Discord Guild (Discord Server) and the Guild Id you provide in the Configuration is valid

**Comment by collectVood** [comment]
From the default configuration file:

```json
...
"Discord": {
        "Bot Token": "",
        "Guild ID": 0, // This here needs to be set
        "Activity type (0 = Playing, 1 = Streaming, 2 = Listening, 3 = Watching)": 0
      },
      ...
```

**Comment by SmokeBudz93** [comment]
where can i find the server id?

**Comment by collectVood** [comment]
![grafik](https://user-images.githubusercontent.com/46131404/106916993-1a164b00-6708-11eb-8862-24d41cad5a5c.png)
Right click the Server Icon in Discord and select "Copy ID". If you don't see the "Copy ID" option, make sure developer mode is enabled.
A guide to enable developer mode can be found here: https://www.discordia.me/en/developer-mode

**Comment by SmokeBudz93** [comment]
thx that all workes but now i cant get the plugin to get permissions i tried all the id's bot nothing seems to give him permissions

**Comment by collectVood** [comment]
Permissions to run commands from discord? 

Here you need to list the persons discord id here in the config for this to work (also restart the bot after you changed the config for it to take affect).

```json
"Can Use Commands Role Ids": [
          0,
          0
        ],```

**Comment by collectVood** [comment]
* my bad, the ids of the discord roles, not your discord id.

**Comment by SmokeBudz93** [comment]
thanks i think its working now i doesnt say no permissions anymore
